/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./BusinessPage.module.css";
import { useNavigate } from "react-router-dom";

function FeatureItem({ iconSrc, text }) {
  return (
    <div className={styles.featureItem}>
      <img src={iconSrc} alt="" className={styles.featureItemIcon} />
      <p className={styles.featureItemText}>{text}</p>
    </div>
  );
}

function ECommerceSolutions() {

  const navigate = useNavigate();

  const handleSignUpClick = () => {
    navigate('/register');
  };

  const features = [
    {
      iconSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/48c37b6cab4cafea2ca99a8d205af189fec3345a53ddf67ceef0d2d0d4b7184c?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Seamless solution for payment collection",
    },
    {
      iconSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/37b70cfe5b2b3e7b2ffcd16e6f5e1a817a7aca6a7176c1b1065ddcd72280148f?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Manage your business anywhere on any device",
    },
    {
      iconSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/e4453d27d3ed5b8662ff17f4235ac64c26c498d3c7a42dc2e16be84fb16bab38?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Personalized operations for your team",
    },
  ];

  return (
    <section className={styles.eCommerceSolutionsSection}>
      <div className={styles.eCommerceSolutionsContent}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/58f1ed1c337f43bf64b643f5bb9462ba1369551d23a143f0a60cf51319e57abb?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920"
          alt="E-Commerce Solutions Illustration"
          className={styles.eCommerceSolutionsImage}
        />
        <div className={styles.eCommerceSolutionsInfo}>
          <h2 className={styles.sectionTitle}>
            Individualized E-Commerce Solutions
          </h2>
          <p className={styles.sectionDescription}>
            Personalize your experience to suit your business's and team's
            specific needs and requirements, and take full advantage of
            swissmoney's internal transfers for a seamless payment collection.
          </p>
          {features.map((feature, index) => (
            <FeatureItem key={index} {...feature} />
          ))}
          <button onClick={handleSignUpClick} className={styles.ctaButton}>Start Operations</button>
        </div>
      </div>
    </section>
  );
}

export default ECommerceSolutions;
