/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import styles from "./FAQ.module.css";

const FAQItem = ({ question, answer }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className={styles.faqItem}>
      <button className={styles.question} onClick={() => setIsOpen(!isOpen)}>
        {question}
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/320d0db485e9368f0d05b2e293dce63f8d077d3bd9e06c490a1ca2d86fcc0e7a?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920"
          alt={isOpen ? "Close" : "Open"}
          className={`${styles.icon} ${isOpen ? styles.iconOpen : ""}`}
        />
      </button>
      {isOpen && <div className={styles.answer}>{answer}</div>}
    </div>
  );
};

function FAQ() {
  const faqData = [
    {
      question: "How can I apply for a swissmoney business account online?",
      answer:
        "Answer to how to apply for a swissmoney business account online.",
    },
    {
      question:
        "What kind of services will I get with my swissmoney business account?",
      answer:
        "Description of services provided with a swissmoney business account.",
    },
    {
      question: "What types of businesses are accepted?",
      answer:
        "Information about the types of businesses accepted by swissmoney.",
    },
    {
      question: "What currencies will I be able to use?",
      answer: "List of currencies supported by swissmoney business accounts.",
    },
    {
      question: "What cryptocurrencies will I be able to use?",
      answer:
        "Information about cryptocurrency support in swissmoney accounts.",
    },
    {
      question: "How can I be sure that my account and my funds are secure?",
      answer:
        "Details about security measures for swissmoney accounts and funds.",
    },
    {
      question: "How does the onboarding process work?",
      answer:
        "Step-by-step explanation of the onboarding process for new accounts.",
    },
    {
      question: "How fast can you onboard a company?",
      answer: "Timeframe for company onboarding with swissmoney.",
    },
    {
      question: "What are the swissmoney business account fees?",
      answer: "Overview of fees associated with swissmoney business accounts.",
    },
    {
      question: "Do you provide OTC services?",
      answer:
        "Information about OTC (Over-The-Counter) services provided by swissmoney.",
    },
  ];

  return (
    <section id="faq" className={styles.faq}>
      <h2 className={styles.title}>FAQ</h2>
      <p className={styles.subtitle}>
        All your questions about Bvnk answered.
      </p>
      <div className={styles.faqList}>
        {faqData.map((item, index) => (
          <FAQItem key={index} question={item.question} answer={item.answer} />
        ))}
      </div>
    </section>
  );
};


export default FAQ;
