/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./BusinessPage.module.css";

function FeatureCard({ iconSrc, title, description }) {
  return (
    <div className={styles.featureCard}>
      <img src={iconSrc} alt="" className={styles.featureIcon} />
      <h3 className={styles.featureTitle}>{title}</h3>
      <p className={styles.featureDescription}>{description}</p>
    </div>
  );
}

function Features() {
  const features = [
    {
      iconSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/e0e816579daf53a15aae65c21112de7bd621dac72a8e32824586b0b2c212cc5c?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
      title: "Boundless Operations",
      description: "Hold full control over your operations anytime, anywhere.",
    },
    {
      iconSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/141fe363ab8f0195af4f70fca97fbc2354ac8f82e831b72889d6d492096c6a50?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
      title: "Near Instant Approval",
      description: "Avoid all unnecessary paperwork and red-tape.",
    },
    {
      iconSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/7df92e84db3a825029216038d34c4e7794fe2c0cf81ca3bfd8abbc08f1b55ad8?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
      title: "Open for Any Business",
      description:
        "Breaking the traditional mold with greater business inclusivity.",
    },
  ];

  return (
    <section className={styles.featuresSection}>
      <div className={styles.featuresContainer}>
        {features.map((feature, index) => (
          <FeatureCard key={index} {...feature} />
        ))}
      </div>
    </section>
  );
}

export default Features;
