/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./BusinessPage.module.css";

function FeatureItem({ iconSrc, text }) {
  return (
    <div className={styles.featureItem}>
      <img src={iconSrc} alt="" className={styles.featureItemIcon} />
      <p className={styles.featureItemText}>{text}</p>
    </div>
  );
}

function GlobalFinancialGateway() {
  const features = [
    {
      iconSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/79f3a54ae7f889e9e738096cbe7179b30cf0c1b61dcb2bf80a82d14e320a2472?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Round-the-clock transactions",
    },
    {
      iconSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/69808783298fe1822c288a3e904ae5235ef81cb26276b219b6303c6a6badd111?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Instant internal and European transfers through SEPA",
    },
    {
      iconSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ec29a6fe0187c57bafa21dacbd07b86dfdcc8f0cd7865f5468b968395e59b30e?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Multi-currency pooling accounts",
    },
  ];

  return (
    <section className={styles.globalFinancialGatewaySection}>
      <div className={styles.globalFinancialGatewayContent}>
        <div className={styles.globalFinancialGatewayInfo}>
          <h2 className={styles.sectionTitle}>
            Your Financial Gateway to the World
          </h2>
          <p className={styles.sectionDescription}>
            Modern business is global. To strive in the current market you can't
            limit your operations, supply-chain, clients or partners to purely
            local borders. We believe that swift operations and a global reach
            is paramount to an active business account.
          </p>
          {features.map((feature, index) => (
            <FeatureItem key={index} {...feature} />
          ))}
          <button className={styles.ctaButton}>Open Account</button>
        </div>
        <img style={{marginTop:"56px"}}
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/cbe169da819092e25b07ac616821bcf5c43aef9e1de712b16498d9ee3bdfedef?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920"
          alt="Global Financial Gateway Illustration"
          className={styles.globalFinancialGatewayImage}
        />
      </div>
    </section>
  );
}

export default GlobalFinancialGateway;
