/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import styles from "./FAQ.module.css";

const FAQItem = ({ question, answer }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className={styles.faqItem}>
      <button className={styles.question} onClick={() => setIsOpen(!isOpen)}>
        {question}
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/320d0db485e9368f0d05b2e293dce63f8d077d3bd9e06c490a1ca2d86fcc0e7a?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920"
          alt={isOpen ? "Close" : "Open"}
          className={`${styles.icon} ${isOpen ? styles.iconOpen : ""}`}
        />
      </button>
      {isOpen && <div className={styles.answer}>{answer}</div>}
    </div>
  );
};

const FAQPersonal = () => {
  const faqData = [
    {
      question: "How can I apply for a personal Unbank account?",
      answer:
        "You can apply for a personal Unbank account by visiting our website and clicking on the 'Open Account' button. Follow the steps to provide the necessary information and documentation.",
    },
    {
      question: "What kind of services will I get with my Unbank account?",
      answer:
        "With a Unbank account, you'll have access to crypto wallets, IBAN accounts, payment cards, and the ability to buy, sell, and exchange cryptocurrencies. You can also make instant transfers and use your crypto for everyday spending.",
    },
    // Add more FAQ items here
  ];

  return (
    <section className={styles.faq} id="faq">
      <h2 className={styles.title}>FAQ</h2>
      <p className={styles.subtitle}>
        All your questions about Unbank answered.
      </p>
      <div className={styles.faqList}>
        {faqData.map((item, index) => (
          <FAQItem key={index} question={item.question} answer={item.answer} />
        ))}
      </div>
    </section>
  );
};

export default FAQPersonal;
