/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./OTCDeskWebsite.module.css";

function EndToEndPlatform() {
  return (
    <section className={styles.endToEndPlatform}>
      <h2 className={styles.sectionTitle}>
        The first <strong>end-to-end</strong> <br />
        <strong>platform in the OTC space</strong>
      </h2>
      <p className={styles.platformDescription}>
        OTCDesk is on track to position itself as a vertical leader by creating
        the first end-to- end platform in the space. Our objective is to ensure
        global reach by targeting trading desks and brokers from across the
        world. The company is founded by a team that has a strong track record
        in crypto, investing, and information technology.
      </p>
    </section>
  );
}

export default EndToEndPlatform;
