/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./OTCDeskWebsite.module.css";

function Footer() {
  return (
    <footer className={styles.footer}>
      <div className={styles.footerContent}>
        <div className={styles.footerLogo}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e99f18b42fef1e8e72feb9dce3c1e58ba0c53c0630ae11fa0c034e9d1005b555?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba"
            alt="OTC Desk Logo"
            className={styles.footerLogoImage}
          />
          <p className={styles.copyright}>
            © 2024 OTCDesk.id - All Rights Reserved
          </p>
        </div>
        <div className={styles.verticalDivider} />
        <div className={styles.socialLinks}>
          <h3 className={styles.socialTitle}>Follow Us</h3>
          <div className={styles.socialIcons}>
            <a href="#" aria-label="Facebook" className={styles.socialIcon}></a>
            <a href="#" aria-label="Twitter" className={styles.socialIcon}></a>
            <a href="#" aria-label="LinkedIn" className={styles.socialIcon}></a>
            <a
              href="#"
              aria-label="Instagram"
              className={styles.socialIcon}
            ></a>
            <a href="#" aria-label="YouTube" className={styles.socialIcon}></a>
          </div>
        </div>
        <div className={styles.verticalDivider} />
        <nav className={styles.footerNav}>
          <h3 className={styles.navTitle}>More Info</h3>
          <a href="#" className={styles.footerLink}>
            Terms of Service
          </a>
          <a href="#" className={styles.footerLink}>
            Privacy Policy
          </a>
          <a href="#" className={styles.footerLink}>
            Fee Structure
          </a>
        </nav>
      </div>
    </footer>
  );
}

export default Footer;
