/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./OTCDeskWebsite.module.css";

function Header() {
  return (
    <header className={styles.header}>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/956da44c4e08c4e4687c77a954cfa944a78185440a78d498b08719a1c8ad0771?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba"
        alt="OTC Desk Logo"
        className={styles.logo}
      />
      <nav className={styles.navigation}>
        <a href="#home" className={styles.navLink}>
          Home
        </a>
        <a href="#company" className={styles.navLink}>
          Company
        </a>
        <a href="#news" className={styles.navLink}>
          News
        </a>
        <button className={styles.contactButton}>Contact Us</button>
      </nav>
    </header>
  );
}

export default Header;
