/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./OTCDeskWebsite.module.css";

function HeroSection() {
  return (
    <section className={styles.heroSection}>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/fa7a6368c1cadf2644f57bccf1d023d986f8885f5753b9fcf398a5934087ab32?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba"
        alt=""
        className={styles.heroBackground}
      />
      <div className={styles.heroContent}>
        <h1 className={styles.heroTitle}>
          Set up your own KYC/AML-compliant OTC Desk.
        </h1>
        <h2 className={styles.heroSubtitle}>
          Give your customers access to <br /> deals instantly. Securely.
        </h2>
        <p className={styles.heroDescription}>
          OTCTrade.com is a white-label solution for exchanges and trading
          desks. The platform connects buyers and sellers who wish to execute
          over the counter deals in a secure way.
        </p>
        <div className={styles.ctaContainer}>
          <button className={styles.primaryCta}>Launch a desk</button>
          <button className={styles.secondaryCta}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/79a07a59e3b02cf08e5b4e335584f8f7a62eead6cc2ebb4373a7f6c08a3e7358?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba"
              alt=""
              className={styles.playIcon}
            />
            Watch Video
          </button>
        </div>
      </div>
    </section>
  );
}

export default HeroSection;
