/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styles from './OTCDeskWebsite.module.css';

function FeatureCard({ icon, title, description }) {
  return (
    <div className={styles.industryFeatureCard}>
      <img src={icon} alt="" className={styles.industryFeatureIcon} />
      <h3 className={styles.industryFeatureTitle}>{title}</h3>
      <p className={styles.industryFeatureDescription}>{description}</p>
    </div>
  );
}

function IndustryFeatures() {
  const features = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/0c87f8d10a20a97c4333b505c0510016647df343bbfb6fa2d20309b91965efd3?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      title: "Exclusive Access to the Best Deals",
      description: "Access quality, exclusive deals securely, right in our platform."
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/095836099236c9730953bf589a6c3775e0ed76cdd823d5355889104ca45baacf?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      title: "Blazing Speed",
      description: "Launch a desk that offers bespoke deals and transactions that settle instantly."
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/f07104e019f9b909ca587d2f96f3de40cb2e9a56609901ed468e2641b323c8bd?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      title: "Each Portfolio Insured to USD 5 million",
      description: "Get peace of mind from any loss due to theft, hacking, or malicious activity. Additional insurance is optionally available."
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/a6a1940ecf9740b3b658c7fc8e3de78b253ac916353c91b21e2503d10d698576?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      title: "Auditable Transactions, Secure Trading Environment",
      Continuing from where we left off:

      description: "Perform background checks and verify each trade and user. Every transaction is audited."
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/01646e3e94409d097cc1a929bad713a321645226f4db38af857d7a2e2337b713?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      title: "Strict Deal Confidentiality",
      description: "Implement strict confidentiality for every offer, deal, and counter-offer within the platform. All transactions handled with a high degree of privacy."
    }
  ];

  return (
    <section className={styles.industryFeatures}>
      <h2 className={styles.sectionTitle}>
        Industry <strong>Leading Features</strong>
      </h2>
      <div className={styles.industryFeatureGrid}>
        {features.map((feature, index) => (
          <React.Fragment key={index}>
            <FeatureCard {...feature} />
            {index < features.length - 1 && <div className={styles.verticalDivider} />}
          </React.Fragment>
        ))}
      </div>
    </section>
  );
}

export default IndustryFeatures;