/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./OTCDeskWebsite.module.css";
import Header from "./Header";
import HeroSection from "./HeroSection";
import UniqueFeatures from "./UniqueFeatures";
import WhitelabelSection from "./WhitelabelSection";
import ProblemSection from "./ProblemSection";
import SolutionSection from "./SolutionSection";
import ProductTour from "./ProductTour";
import IndustryFeatures from "./IndustryFeatures";
import TrustedPartners from "./TrustedPartners";
import EndToEndPlatform from "./EndToEndPlatform";
import Footer from "./Footer";

function OTCDeskWebsite() {
  return (
    <div className={styles.otcDeskWebsite}>
      <hr className={styles.horizontalDivider} />
      <main className={styles.mainContent}>
        <Header />
        <HeroSection />
        <UniqueFeatures />
        <WhitelabelSection />
        <ProblemSection />
        <SolutionSection />
        <ProductTour />
        <IndustryFeatures />
        <TrustedPartners />
        <EndToEndPlatform />
      </main>
      <Footer />
    </div>
  );
}

export default OTCDeskWebsite;
