/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./OTCDeskWebsite.module.css";

function SolutionCard({ icon, description }) {
  return (
    <div className={styles.solutionCard}>
      <div className={styles.solutionIconWrapper}>
        <img src={icon} alt="" className={styles.solutionIcon} />
      </div>
      <p className={styles.solutionDescription}>{description}</p>
    </div>
  );
}

function SolutionSection() {
  const solutions = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/a082aeb61766b39351af02405ca7eb87c2fab522599ad7bcee6755cc66b3be41?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      description:
        "High transaction volume platform featuring a pool of available deals enabling direct trading",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/805bb171d42778fd1f44f394be07ed99f80230e7a6cb8dd9ab8b6eff32408fb3?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      description: "Customizable audience search & advanced analytics tools",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/2386dc38f99ca960b10338deb29bb41030534578b770f8b027b8536144102d24?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      description: "Global network of verified traders and trading desks",
    },
  ];

  return (
    <section className={styles.solutionSection}>
      <h2 className={styles.sectionTitle}>
        The <strong>Solution</strong>
      </h2>
      <div className={styles.solutionGrid}>
        {solutions.map((solution, index) => (
          <SolutionCard key={index} {...solution} />
        ))}
      </div>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/e4f483ddbac7f669956230411238356cb31766396bf4f9625dd8e0863bf6d5d3?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba"
        alt=""
        className={styles.solutionDecoration1}
      />
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/bcac26e20b153efb3b464385c256960f1b9f08fb1167efd7833d04a3e3b03da5?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba"
        alt=""
        className={styles.solutionDecoration2}
      />
    </section>
  );
}

export default SolutionSection;
