/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./OTCDeskWebsite.module.css";

function TrustedPartners() {
  const partners = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/44609c102ca696e992eaf1495aab7b6eb641401a1bb76e1d8917e8f58265c055?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      alt: "Partner 1 logo",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/3629eec351c1e33cba3f724b2ae4a62ae4a70c9ce964e913c3f9a2b31e8cfd76?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      alt: "Partner 2 logo",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/6215f3425f44b38c2b7aff45d80a0a94ac968425c50541858338dc28e5a871c2?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      alt: "Partner 3 logo",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/4c61a8a0719b76d0261db27292399bd44bbf88147cccf6cb455f8227cb33d540?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      alt: "Partner 4 logo",
    },
  ];

  return (
    <section className={styles.trustedPartners}>
      <h2 className={styles.sectionTitle}>
        Our <strong>Trusted Partners</strong>
      </h2>
      <p className={styles.partnerDescription}>
        Companies that are helping us build the greatest over-the-counter
        platform of all time.
      </p>
      <div className={styles.partnerLogos}>
        {partners.map((partner, index) => (
          <React.Fragment key={index}>
            <img
              src={partner.src}
              alt={partner.alt}
              className={styles.partnerLogo}
            />
            {index < partners.length - 1 && (
              <div className={styles.verticalDivider} />
            )}
          </React.Fragment>
        ))}
      </div>
    </section>
  );
}

export default TrustedPartners;
