/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./OTCDeskWebsite.module.css";

function FeatureCard({ icon, title, description }) {
  return (
    <div className={styles.featureCard}>
      <img src={icon} alt="" className={styles.featureIcon} />
      <h3 className={styles.featureTitle}>{title}</h3>
      <p className={styles.featureDescription}>{description}</p>
    </div>
  );
}

function UniqueFeatures() {
  const features = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/a2989e4570f7a821bcf947bab0b740895a2e1603f867e94badf92e0f9637ee9a?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      title: "Verified traders",
      description:
        "Verify every trader, exchange, and trading desk that signs up on the platform and perform background checks (KYC, AML) to avoid scams.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/aace0d55da969269f30504d91b63c86b9ff5f444693517fb307fc3c204a576a6?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      title: "Guaranteed transactions",
      description:
        "Move funds in seconds with multi-party computation, a solution that enables the secure transfer of digital assets and guarantees transactions.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/87973c01d488c7d26177346a83c0a0be1d13ab81f9352a8c770a6353950ec6d7?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba",
      title: "Instant Settlement",
      description:
        "Faster settlement timing for both crypto to crypto and fiat to crypto deals. Funds will be swapped in the traders' accounts instantly.",
    },
  ];

  return (
    <section className={styles.uniqueFeatures}>
      <h2 className={styles.sectionTitle}>
        What makes OTCDesk <strong>unique</strong>
      </h2>
      <div className={styles.featureGrid}>
        {features.map((feature, index) => (
          <React.Fragment key={index}>
            <FeatureCard {...feature} />
            {index < features.length - 1 && (
              <div className={styles.verticalDivider} />
            )}
          </React.Fragment>
        ))}
      </div>
    </section>
  );
}

export default UniqueFeatures;
