/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./OTCDeskWebsite.module.css";

function WhitelabelSection() {
  return (
    <section className={styles.whitelabelSection}>
      <div className={styles.whitelabelContent}>
        <h2 className={styles.whitelabelTitle}>
          Whitelabel OTCDesk's <br /> Platform Today.
        </h2>
        <h3 className={styles.whitelabelSubtitle}>
          And, connect with other whitelabelled OTCDesk desks <br />
          to expand your deal network.
        </h3>
        <p className={styles.whitelabelDescription}>
          Save months and years of development time and costs. Instantly set up
          your own world-class trading desk and customize it with your own
          branding. This P2P solution is even ideal for existing exchanges
          because OTCDesk eliminates real and perceived conflicts of interest
          associated with non-transparency, intermediaries posing as
          counterparties. Buyers deal directly with sellers.
        </p>
      </div>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/3023d8fd5fc7616de98a9ae00b13f5905e63b55c9c7fd194a22d8db8d2d69bb6?placeholderIfAbsent=true&apiKey=d04c07a3696b4df490c9872df5c4d2ba"
        alt="OTC Desk Platform Interface"
        className={styles.whitelabelImage}
      />
    </section>
  );
}

export default WhitelabelSection;
