/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Hero.module.css";
import Button from "../Button/Button";
import { useNavigate, useLocation } from 'react-router-dom';


const Hero = () => {

  const navigate = useNavigate();

  const handleSignUpClick = () => {
    navigate('/register');
  };

  return (
    <section style={{paddingRight:"0px", paddingLeft:"0px"}} className={styles.hero}>
      <div className={styles.heroContent}>
        <div className={styles.textContent}>
          <h1 className={styles.heading}>
          Ultra-Fast Payments <br /> Between Crypto and Bank
          </h1>
          <p className={styles.subheading}>
            Be empowered to send, spend, and manage your digital assets <br />{" "}
            anytime, anywhere.
          </p>
          <Button variant="primary" onClick={handleSignUpClick} className={styles.ctaButton}>
            Open Account
          </Button>
        </div>
        <div className={styles.imageWrapper}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/c5ab8854f1f1b93e4ee079d5f305b6d9bde3616aff057d02e790e2a47f1e1e94?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920"
            alt="Crypto spending illustration"
            className={styles.heroImage}
          />
        </div>
      </div>
    </section>
  );
};

export default Hero;
