/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../Header/Header";
import Hero from "../Hero/Hero";
import Stats from "../Stats/Stats";
import Features from "../Features/Features";
import SecurityFeatures from "../SecurityFeatures/SecurityFeatures";
import ProductSection from "../ProductSection/ProductSection";
import GetStarted from "../GetStarted/GetStarted";
import FAQ from "../FAQ/FAQ";
import ContactForm from "../ContactForm/ContactForm";
import Footer from "../Footer/Footer";
import styles from "./App.module.css";
import { Routes, Route, Navigate } from 'react-router-dom';
import FAQPersonal from "../FAQ/FAQ";


const PersonalPage = () => {
  const cryptoWalletFeatures = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8355b5b7bd3f5a70061be6cc20c4265694c36b3d0fc02b69f6b7a679735a123c?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Buy, sell and exchange the most popular cryptocurrencies",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6360412bb79d423e07cbdb24f82ca0d187342d823346673f64def0b3e1bbed37?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Transfer crypto from third parties to store on swissmoney",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/bf56d3d6814cda8197ab387affcee883e71db1a06318bb9a0c50b82b115e6021?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Instantl=y exchange crypto to fiat funds on your account",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8599a2885c1fed1bdc2fcb540eee85f81445e541fa1e9ec4bb693cb7ba448f7b?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Low fees make it ideal for larger volume off-ramping",
    },
  ];

  const ibanAccountFeatures = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/d54c5e2b0439c89ab7059cfa149a429ffcb8b49ea080da9488c3e635965c3dad?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Take out one or more dedicated IBAN accounts",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/a50a5d3af3f3519c160f0c40fbcf8c24b9216bf1747ded1f8450f1bb5e65a369?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Enjoy instant transfers across Europe via SEPA",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/ff3714b9b0ebbf4bdb470cb1cd4d866544b1601d7450f3d8c5994dc8ff952445?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Forget the constant red-tape associated with legacy banking institutions and enjoy seamless and uninterrupted transfers",
    },
  ];

  const paymentCardFeatures = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/2fe153807666d7bef9d7e02927f32625af58098480de7a966da4bf12d63ecf21?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Forget the hassle of wire transfers with limitless card spending",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/2b628fd27d6b04d79e9826aeb174ea5d228275e68fac0d26834de7a4fd21a9f2?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Take out multiple payment cards for different spending needs",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/c56ccde5861da2118e8ec854bff55fd845ccd6b868d1f663cc9fe6afaea3c85c?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Sync with Google Pay or Apple Pay and enjoy contactless spending on the go",
    },
  ];

  const businessAccountFeatures = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/ae83f5a84737de47da9990f62b4f1ec1a36f658f60bb707a87a4087bd72ea302?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Dedicated swissmoney specialists will work with you to streamline the onboarding process",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/5068b9c0ddf40b23c755183799c1354761460261fc3ad9e052b6f43403ace80e?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Personalize operations to best suit the needs of your team and company",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/ba5a36d6c41240d59983edbb6569d5b938dd73e7f90be1992cf17a50aa4731e8?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      text: "Unlike legacy financial institutions, a larger variety of industries and businesses accepted",
    },
  ];

  return (
    <div className={styles.app}>
      <Header />

      <main>
        <Hero />
        <Stats />
        <Features />
        <SecurityFeatures />
<ProductSection
  id="services" // Tambahkan ID disini
  title="Crypto Wallets"
  description="Make payments with crypto by instantly exchanging it for fiat funds on your card."
  features={cryptoWalletFeatures}
  buttonText="Create Wallet"
  imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/0e2084a7bc9bc5a322c3edcee63422f5f645337bfb46d59d08af26600cabf290?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920"
  imageAlt="Crypto Wallet Illustration"
/>

        <ProductSection
          title="Business Accounts"
          description="Scale your business to a truly global reach with cross border facilitation, and hold your company's finances in fiat, crypto or both."
          features={businessAccountFeatures}
          buttonText="Open Account"
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/e15062eefd1f192065790e6048473b7098e37abe891ba422ff6adcfd7a28fb27?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920"
          imageAlt="Business Account Illustration"
          reverse
        />
        <GetStarted />
        <FAQPersonal />
        <ContactForm />
      </main>
      <Footer />
    </div>
  );
};

export default PersonalPage;
