/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./OrderTable.module.css";
import TableHeader from "./TableHeader";
import TableRow from "./TableRow";
import Pagination from "./Pagination";

const orderData = [
  {
    id: "#20462",
    product: {
      name: "Hat",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/cd3d2f4be68d2a3eaea8d61193efd45106a97af5dbbcb3b4168b95880c6e0f29?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
    },
    customer: "Matt Dickerson",
    date: "13/05/2022",
    amount: "$4.95",
    paymentMode: "Tranfer Bank",
    status: "Delivered",
  },
  {
    id: "#18933",
    product: {
      name: "Laptop",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/a4ab021e99e4f21cf33fec04ddff756ececeafc086757b4feccfaecb125210fd?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
    },
    customer: "Wiktoria",
    date: "22/05/2022",
    amount: "$8.95",
    paymentMode: "Cash on Delivery",
    status: "Delivered",
  },
  {
    id: "#45169",
    product: {
      name: "Phone",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/b7ba9af2acc1c9378064d28e88f1411f1a54ad837f99df52c9d1734b4ce18811?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
    },
    customer: "Trixie Byrd",
    date: "15/06/2022",
    amount: "$1,149.95",
    paymentMode: "Cash on Delivery",
    status: "Process",
  },
  {
    id: "#34304",
    product: {
      name: "Bag",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/903b27c4855bd5e3526bac6f8dbf797dfde222fa749c8498b921d1824aa1aae4?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
    },
    customer: "Brad Mason",
    date: "06/09/2022",
    amount: "$899.95",
    paymentMode: "Tranfer Bank",
    status: "Process",
  },
  {
    id: "#17188",
    product: {
      name: "Headset",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/46ce363a26e9a8e2b69026a1468d2f774c9fedb1404ab845496fbae656a21d47?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
    },
    customer: "Sanderson",
    date: "25/09/2022",
    amount: "$22.95",
    paymentMode: "Cash on Delivery",
    status: "Canceled",
  },
  {
    id: "#73003",
    product: {
      name: "Mouse",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/325dd3d376be08a7eb51588d4479bb6840842198d7ae4055719db4b3e8982d2d?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
    },
    customer: "Jun Redfern",
    date: "04/10/2022",
    amount: "$54.95",
    paymentMode: "Tranfer Bank",
    status: "Delivered",
  },
  {
    id: "#58825",
    product: {
      name: "Clock",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/bfc350e93f92bd9e0ba67e3f986d1ec7e620f863d59118fd75a3dcaebb55e869?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
    },
    customer: "Miriam Kidd",
    date: "17/10/2022",
    amount: "$174.95",
    paymentMode: "Tranfer Bank",
    status: "Delivered",
  },
  {
    id: "#44122",
    product: {
      name: "T-shirt",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/65fe67689eab4331045adb9f1dc5484196b62cef6b487b5f6d13d8726228ed1a?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
    },
    customer: "Dominic",
    date: "24/10/2022",
    amount: "$249.95",
    paymentMode: "Cash on Delivery",
    status: "Delivered",
  },
  {
    id: "#89094",
    product: {
      name: "Monitor",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/45e097153b1ea5d367aedaffd9efdd63a0123e101ca26cb5c4ecbed4444e4dd5?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
    },
    customer: "Shanice",
    date: "01/11/2022",
    amount: "$899.95",
    paymentMode: "Tranfer Bank",
    status: "Canceled",
  },
  {
    id: "#85252",
    product: {
      name: "Keyboard",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/99c9a3c018e9482e4f7e2d69f785396584af4f35e2030cc544c663c55c228624?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920",
    },
    customer: "Poppy-Rose",
    date: "22/11/2022",
    amount: "$6.948",
    paymentMode: "Tranfer Bank",
    status: "Process",
  },
];

function OrderTable() {
  return (
    <section className={styles.orderTable}>
      <TableHeader />
      <table className={styles.table}>
        <thead>
          <tr className={styles.tableHead}>
            <th>Tracking ID</th>
            <th>Product</th>
            <th>Customer</th>
            <th>Date</th>
            <th>Amount</th>
            <th>Payment Mode</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {orderData.map((order, index) => (
            <TableRow key={order.id} order={order} isEven={index % 2 === 0} />
          ))}
        </tbody>
      </table>
      <Pagination />
    </section>
  );
}

export default OrderTable;
