/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./OrderTable.module.css";

function Pagination() {
  return (
    <nav className={styles.pagination} aria-label="Table navigation">
      <button className={styles.paginationBtn}>Previous</button>
      <button className={`${styles.paginationBtn} ${styles.active}`}>1</button>
      <button className={styles.paginationBtn}>2</button>
      <button className={styles.paginationBtn}>3</button>
      <button className={styles.paginationBtn}>Next</button>
    </nav>
  );
}

export default Pagination;
