/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./OrderTable.module.css";

function TableRow({ order, isEven }) {
  const rowClass = isEven ? styles.evenRow : styles.oddRow;
  const statusClass = styles[order.status.toLowerCase()];

  return (
    <tr className={`${styles.tableRow} ${rowClass}`}>
      <td>{order.id}</td>
      <td className={styles.productCell}>
        <img
          src={order.product.image}
          alt={order.product.name}
          className={styles.productImage}
        />
        <span>{order.product.name}</span>
      </td>
      <td>{order.customer}</td>
      <td>{order.date}</td>
      <td>{order.amount}</td>
      <td>{order.paymentMode}</td>
      <td>
        <span className={`${styles.status} ${statusClass}`}>
          {order.status}
        </span>
      </td>
      <td className={styles.actionCell}>
        <button className={styles.actionBtn}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f901d235a084af91f88aaf84240da5cd68a3a65d6acf65fd758a042a07e14884?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920"
            alt="Edit"
            className={styles.actionIcon}
          />
        </button>
        <button className={styles.actionBtn}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/5734b94142dc21f83ebf8ef398251369bcf214ebf73c212f4f5b0ca6d2c12648?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920"
            alt="Delete"
            className={styles.actionIcon}
          />
        </button>
      </td>
    </tr>
  );
}

export default TableRow;
