/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./OrderTable.module.css";

function TableHeader() {
  return (
    <header className={styles.tableHeader}>
      <div className={styles.entriesWrapper}>
        <label htmlFor="showEntries" className={styles.entriesLabel}>
          Show
        </label>
        <div className={styles.entriesSelect}>
          <select id="showEntries" className={styles.entriesDropdown}>
            <option>10</option>
          </select>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/13cd18d08643a187edd2efa595b82365a2b0ce7a8b647eaa726b21eac67002da?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920"
            alt=""
            className={styles.dropdownArrow}
          />
        </div>
        <span className={styles.entriesText}>entries</span>
      </div>
      <div className={styles.searchWrapper}>
        <input
          type="text"
          placeholder="Search..."
          className={styles.searchInput}
        />
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c230e2fc037f338a838241a8951cd0ab7120391f7d21169357ed2af9693669e2?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920"
          alt="Search"
          className={styles.searchIcon}
        />
      </div>
      <button className={styles.addCustomerBtn}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/871fbd76bdcca76790f42cdbce683f527f73498171b5b303feeb73bd71a731aa?placeholderIfAbsent=true&apiKey=e3ddd6dd58b748b09fc1391939743920"
          alt=""
          className={styles.addIcon}
        />
        Add Customer
      </button>
    </header>
  );
}

export default TableHeader;
