/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Features.module.css";

const Features = () => {
  const features = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7a06ae2b92ceae373f8f2eb92dfa7bf513bb87b1b2341ad380b2cf66b1cc696e?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      title: "Fast and Easy to Use",
      description:
        "Full day-to-day functionality for both crypto and fiat made fast and easy.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/ed038bcd622702c0595027792f441609c2172b3460476899341bd4d89e67b35c?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      title: "Crypto Spendability",
      description:
        "Instantly top-up your card with your crypto assets for seamless spending.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/ecc51e6118bbdd0207e6e21b222b9d994413f0b31ee76d4088a90f9565aef05e?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      title: "Zero Monthly Fees",
      description:
        "No hidden or recurring fees. Only pay for the services you use.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6ba535d8687509bdd988046adf91e00ba6302c6774ce202ee85f3b236545fbb2?apiKey=e3ddd6dd58b748b09fc1391939743920&&apiKey=e3ddd6dd58b748b09fc1391939743920",
      title: "Zero Spending Limits",
      description:
        "Customize your payment cards and raise the spending limit as much as you like.",
    },
  ];

  return (
    <section className={styles.features}>
      <h2 className={styles.featuresTitle}>Why Choose Bvnk?</h2>
      <div className={styles.featuresList}>
        {features.map((feature, index) => (
          <div key={index} className={styles.featureItem}>
            <img src={feature.icon} alt="" className={styles.featureIcon} />
            <h3 className={styles.featureTitle}>{feature.title}</h3>
            <p className={styles.featureDescription}>{feature.description}</p>
          </div>
        ))}
      </div>
    </section>
  );
};

export default Features;
